"""Terraform IaC generator tool."""
from __future__ import annotations

from langchain_core.tools import tool


@tool
def generate_terraform(incident_type: str, component: str, ip_address: str = "192.168.10.45") -> str:
    """Generate declarative Terraform security rules for Huawei Cloud based on incident type.
    Returns HCL code for WAF rules, Security Group rules, or container governance.
    Example: generate_terraform("SQL Injection", "auth", "192.168.10.45")"""
    if "sql" in incident_type.lower() or component == "auth":
        return f"""# Huawei Cloud WAF & Security Group Declarative Rule
resource "huaweicloud_waf_rule_blacklist" "block_sqli_attacker" {{
  policy_id   = "policy_production_waf_01"
  name        = "AutoBlock_SQLi_Vector"
  ip_address  = "{ip_address}"
  action      = "block"
  description = "Autonomously generated by Huawei MaaS Triage Agent"
}}

resource "huaweicloud_networking_secgroup_rule" "isolate_auth_port" {{
  security_group_id = "sg_production_auth"
  direction         = "ingress"
  ethertype         = "IPv4"
  protocol          = "tcp"
  port_range_min    = 3000
  port_range_max    = 3000
  remote_ip_prefix  = "{ip_address}/32"
  action            = "deny"
}}"""
    elif "mongo" in incident_type.lower() or component == "database":
        return """# Database & VPC Peering Security Rule
resource "huaweicloud_vpc_route" "db_egress_route" {{
  vpc_id      = var.vpc_id
  destination = "0.0.0.0/0"
  type        = "peering"
  nexthop     = var.peering_id
}}"""
    else:
        return """# Container Resource Governance Policy (Cgroups)
resource "huaweicloud_cce_node_pool" "scale_memory_pool" {{
  cluster_id         = var.cce_cluster_id
  name               = "pool-auto-resilient"
  flavor_id          = "c7.xlarge.4"
  initial_node_count = 3
  os                 = "EulerOS 2.9"
}}"""
